# Generated by Django 5.0.4 on 2024-04-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_participant_client_id_event_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('num_res', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'En attente'), ('Confirmed', 'Confirmée'), ('Cancelled', 'Annulée')], max_length=20)),
            ],
        ),
    ]
