# Generated by Django 5.0.4 on 2024-05-01 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_id_client_client_id_rename_id_client_event_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='id',
            new_name='id_cl',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='id',
            new_name='id_cl',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='id',
            new_name='id_cl',
        ),
    ]
