# Generated by Django 5.0.4 on 2024-05-01 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_id_client_id_cl_rename_id_event_id_cl_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='id_cl',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='id_cl',
            new_name='client',
        ),
    ]
