# Generated by Django 5.0.4 on 2024-05-01 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rapport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestataire',
            fields=[
                ('num_pres', models.AutoField(primary_key=True, serialize=False)),
                ('nom_pres', models.CharField(max_length=100)),
                ('prenom_pres', models.CharField(max_length=100)),
                ('num_telpres', models.CharField(max_length=20)),
                ('Prestataire', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
