# Generated by Django 5.0.4 on 2024-05-01 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_prestataire'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestataire',
            old_name='Prestataire',
            new_name='Event',
        ),
    ]
