# Generated by Django 5.0.4 on 2024-05-05 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_compte_reservations_alter_compte_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapport',
            name='date_rapp',
            field=models.DateField(),
        ),
    ]
