# Generated by Django 5.0.4 on 2024-05-06 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_rapport_date_rapp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestataire',
            old_name='nom_pres',
            new_name='nom_prestataire',
        ),
        migrations.RenameField(
            model_name='prestataire',
            old_name='num_pres',
            new_name='num_prestataire',
        ),
        migrations.RenameField(
            model_name='prestataire',
            old_name='num_telpres',
            new_name='num_tel',
        ),
        migrations.RenameField(
            model_name='prestataire',
            old_name='prenom_pres',
            new_name='prenom_prestataire',
        ),
    ]
