# Generated by Django 5.0.4 on 2024-05-06 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_rename_nom_pres_prestataire_nom_prestataire_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='Paiement',
        ),
        migrations.AddField(
            model_name='paiement',
            name='client',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.client'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(),
        ),
    ]
