# Generated by Django 5.0.4 on 2024-05-11 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_remove_client_paiement_paiement_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='event',
            name='titre',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('Wedding', 'Mariage'), ('Birthday', 'Anniversaire'), ('Corporate', "Événement d'entreprise"), ('Conference', 'Conférence'), ('Exhibition', 'Exposition'), ('Baptism', 'Baptême'), ('Gender Reveal', 'Révélation de genre')], max_length=100),
        ),
        migrations.AlterField(
            model_name='paiement',
            name='mode_de_paiement',
            field=models.CharField(choices=[('espece', 'Espèces'), ('carte', 'Carte de crédit'), ('cheque', 'Chèque'), ('virement', 'Virement bancaire')], max_length=100),
        ),
    ]
