# Generated by Django 5.0.4 on 2024-05-11 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_remove_event_participants_alter_event_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='client',
        ),
    ]
