# Generated by Django 5.0.4 on 2024-05-12 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_rename_lieu_event_adress_rename_titre_event_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('Wedding', 'Wedding'), ('Birthday', 'Birthday'), ('Conference', 'Conference'), ('Exhibition', 'Exhibition'), ('Baptism', 'Baptism'), ('Gender Reveal', 'Gender Reveal')], max_length=100),
        ),
    ]
