# Generated by Django 5.0.4 on 2024-05-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_event_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='adresse',
            new_name='adress',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='num_tel',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='nom',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='prenom',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='adresse',
            new_name='adress',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='nom',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='id_invité',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='prenom',
            new_name='last_prenom',
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('Wedding', 'Wedding'), ('Birthday', 'Birthday'), ('Conference', 'Conference'), ('Graduation', 'Graduation'), ('Baptism', 'Baptism'), ('Gender Reveal', 'Gender Reveal')], max_length=100),
        ),
    ]
