# Generated by Django 5.0.4 on 2024-05-13 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contact_us',
        ),
    ]
